services:
  elemm-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/v3rm1ll1on/elemm:latest
    container_name: elemm-gateway
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - elemm-config:/root/.elemm
    environment:
      - HOST=0.0.0.0
      - PORT=8090

volumes:
  elemm-config:
    driver: local
